# Generated by Django 5.0.3 on 2024-05-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('r', 'Romance'), ('t', 'Thriller'), ('k', 'Classic'), ('d', 'Drama'), ('History', 'h')], max_length=8),
        ),
    ]
