# Generated by Django 5.0.3 on 2024-05-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('r', 'Romance'), ('t', 'Thriller'), ('k', 'Classic'), ('d', 'Drama'), ('h', 'History')], max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('h', 'hardCover'), ('s', 'softCover')], max_length=2),
        ),
    ]
